fix `openid` scope issue as client is requesting for `id_token`
curityio/react-assisted-token-website pull request #20
Opened 2021-01-06 19:57 UTC by KhizerRehan

This PR fix the `infinite` loop issue due to missing of providing scope of `openid` As client request is asking for the `respones_type=id_token`

2021-01-07 09:02 UTC, travisspencer requested changes

2021-01-07 09:02 UTC, travisspencer commented on README.md
> +   `opendid` scope.
typo

2021-01-07 09:15 UTC, KhizerRehan commented on README.md
> +   `opendid` scope.
Good Catch! Thanks

2021-01-07 09:43 UTC, Waseem826 requested changes
Screenshot for `openid` scope should be consistent with other screenshots (.i.e no top nav bar and full width)

2021-01-07 09:43 UTC, Waseem826 commented on README.md
> +   `openid` scope.
Move this to previous line

2021-01-07 09:43 UTC, Waseem826 commented on README.md
> +7. `Validate` and `Commit` the changes and you are all setup.
No need to say `Validate` here. 
```suggestion
7. Commit the changes and you are all setup.
```

2021-01-07 10:40 UTC, Waseem826 approved these changes

2021-01-08 09:10 UTC, travisspencer approved these changes

2021-01-08 09:13 UTC, merged